version: "3.8"
services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - topeducation1
      - topeducation2
      - topeducation3

  mysql-db:
    image: mysql
    restart: always
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 2190
      MYSQL_DATABASE: topedu
    ports:
      - 33060:3306

  topeducation1:
    container_name: project-topeducation1
    image: aracelyu/tingeso1
    ports:
      - "8091:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/topedu?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=2190
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - mysql-db

  topeducation2:
    container_name: project-topeducation2
    image: aracelyu/tingeso1
    ports:
      - "8092:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/topedu?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=2190
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - mysql-db


  topeducation3:
    container_name: project-topeducation3
    image: aracelyu/tingeso1
    ports:
      - "8093:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/topedu?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=2190
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - mysql-db
