pipeline{
    agent any
    tools{
        maven "maven"
    }
    stages{

        stage("Build JAR FILE"){
            steps{
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/AracelyU/Entrega-Tingeso-1']])
                dir("TopEducation"){
                    sh "mvn clean install"
                }
            }
        }

        stage("Test"){
            steps{
                dir("TopEducation"){
                    sh "mvn test"
                }
            }

        }

        stage("Built Docker Image"){
            steps{
                dir("TopEducation"){
                    sh "docker build -t aracelyu/tingeso1 ."
                }
            }
        }

        stage("Push Docker Image"){
            steps{
                dir("TopEducation"){
                    withCredentials([string(credentialsId: 'dckrhubpassword2', variable: 'dckpass')]) {
                        sh "docker login -u aracelyu -p ${dckpass}"

                    }
                    sh "docker push aracelyu/tingeso1"

                }

            }
        }

    }
    post{
        always{
            dir("TopEducation"){
                sh "docker logout"
            }
        }
    }

}